# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.create(title: 'BLOGGY BLOG', body: 'Hey this is my blog post, OMG you should totally read it! It is like the best blog post ever! OMG OMG OMG OMG OMG OMG OMG OMG OMG OMG!', author_id: 1)
Post.create(title: 'Another Test Blog Post', body: "This is a test. I am currently formatting the blog page. Taxidermy kinfolk flannel keffiyeh blue bottle, ennui chicharrones pug wolf selvage kogi put a bird on it fixie beard yr. Pinterest williamsburg deep v narwhal, DIY mumblecore shoreditch meh hoodie next level trust fund yr. Poutine irony cred forage. Microdosing artisan twee, poutine pug affogato sustainable williamsburg hashtag marfa post-ironic seitan pour-over four dollar toast taxidermy. Blue bottle XOXO kickstarter locavore tilde, put a bird on it direct trade gastropub cronut authentic blog artisan taxidermy. Godard keytar cliche, mixtape cray asymmetrical pork belly kickstarter raw denim flannel squid jean shorts four dollar toast. Slow-carb yuccie kitsch chicharrones tumblr offal.

Lomo godard bicycle rights post-ironic everyday carry marfa, church-key DIY. Chicharrones vice man braid yr fashion axe lo-fi, aesthetic photo booth. Gluten-free keffiyeh whatever trust fund, iPhone knausgaard dreamcatcher ugh disrupt listicle sustainable. Disrupt forage man bun messenger bag. VHS bushwick pinterest migas keytar, street art brunch chicharrones pug narwhal food truck freegan paleo ugh. +1 pickled pop-up hella, flannel literally photo booth farm-to-table. Normcore thundercats before they sold out, pinterest synth direct trade etsy migas swag williamsburg schlitz hashtag.

Try-hard kogi sriracha, cold-pressed tilde bitters aesthetic squid migas leggings mumblecore williamsburg godard. Twee listicle kombucha post-ironic raw denim bespoke. Banh mi knausgaard raw denim, artisan hashtag 8-bit plaid bicycle rights crucifix. Tofu mustache marfa, pabst dreamcatcher iPhone fashion axe four loko literally lomo. Meh sartorial meditation kogi PBR&B blue bottle. Church-key sustainable vinyl, master cleanse echo park etsy four dollar toast listicle brunch. Austin try-hard tilde williamsburg DIY iPhone.

Jean shorts fap meggings stumptown raw denim, gochujang wolf vegan put a bird on it umami squid small batch. Yuccie mlkshk williamsburg, pour-over pickled umami cardigan scenester austin. Occupy synth kombucha, tote bag swag skateboard helvetica drinking vinegar twee. Gentrify vegan marfa pour-over, deep v bicycle rights iPhone slow-carb 90's authentic cold-pressed chartreuse neutra synth. Mumblecore gochujang jean shorts keytar, thundercats franzen chartreuse knausgaard readymade tacos pickled church-key plaid man bun actually. Kale chips synth sartorial seitan photo booth. Schlitz ethical artisan waistcoat disrupt, dreamcatcher distillery cold-pressed vice kale chips chicharrones irony taxidermy bicycle rights.", author_id: 1)